In [12]:
import numpy as np

class VectorQuantificacao:
    def __init__(self, input_size, num_neurons, learning_rate=0.1, num_epochs=100):
        self.input_size = input_size
        self.num_neurons = num_neurons
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        # Inicialização dos pesos dos neurônios
        self.weights = np.random.rand(num_neurons, input_size)
      
        
    def train(self, data):
        for epoch in range(self.num_epochs):
            for x in data:
                # Encontre o neurônio vencedor (o mais próximo do ponto de entrada)
                winner_index = self._find_winner(x)

                # Atualize os pesos do neurônio vencedor
                self.weights[winner_index] += self.learning_rate * (x - self.weights[winner_index])
                
    def _find_winner(self, x):
        # Calcule as distâncias entre o ponto de entrada e os pesos de todos os neurônios
        distances = np.linalg.norm(self.weights - x, axis=1)
        
        # Encontre o índice do neurônio com a menor distância (o vencedor)
        winner_index = np.argmin(distances)
        return winner_index

# Define o conjunto de dados de entrada
data = np.array([[0.1, 0.2, 0.3],
                 [0.5, 0.6, 0.7],
                 [0.9, 0.8, 0.7]])

# Cria e treina o vetor quantizado
vq = VectorQuantificacao(input_size=3, num_neurons=5, learning_rate=0.1, num_epochs=100)
vq.train(data)

# Imprime os pesos dos neurônios após o treinamento
print("Pesos dos neurônios após o treinamento:")
print(vq.weights)


Pesos dos neurônios após o treinamento:
[[0.3415965  0.90760534 0.62622018]
 [0.03489449 0.67447237 0.66836891]
 [0.71052632 0.70526316 0.7       ]
 [0.10000389 0.20000832 0.29999257]
 [0.36724168 0.95761153 0.8992746 ]]
